version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/vaultwarden"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/bootstrap"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
