# NOTE: Vaultwarden also accepts a pre-hashed ADMIN_TOKEN (argon2 PHC string,
# via `vaultwarden hash`) for extra defense-in-depth. This uses a long random
# plaintext token for simplicity; consider hashing it if you want to harden
# the admin credential further.
resource "random_password" "admin_token" {
  length  = 48
  special = false
}

resource "google_secret_manager_secret" "admin_token" {
  project   = var.project_id
  secret_id = "vaultwarden-admin-token"

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "admin_token" {
  secret      = google_secret_manager_secret.admin_token.id
  secret_data = random_password.admin_token.result
}

resource "google_secret_manager_secret" "tailscale_authkey" {
  project   = var.project_id
  secret_id = "vaultwarden-tailscale-authkey"

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "tailscale_authkey" {
  secret      = google_secret_manager_secret.tailscale_authkey.id
  secret_data = tailscale_tailnet_key.vm.key
}

# SMTP credentials are issued externally by the mail relay provider (Brevo),
# not generated by Terraform - same reasoning as tailscale_oauth_client_id/
# secret, just persisted as a VM-readable secret instead of provider-only.
resource "google_secret_manager_secret" "smtp_username" {
  project   = var.project_id
  secret_id = "vaultwarden-smtp-username"

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "smtp_username" {
  secret      = google_secret_manager_secret.smtp_username.id
  secret_data = var.smtp_username
}

resource "google_secret_manager_secret" "smtp_password" {
  project   = var.project_id
  secret_id = "vaultwarden-smtp-password"

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "smtp_password" {
  secret      = google_secret_manager_secret.smtp_password.id
  secret_data = var.smtp_password
}

# rsync daemon password for the NAS backup account, issued externally on the
# NAS itself (same externally-issued-credential reasoning as smtp_username/
# password above), persisted here so the VM can fetch it at boot.
resource "google_secret_manager_secret" "nas_backup_password" {
  project   = var.project_id
  secret_id = "vaultwarden-nas-backup-password"

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "nas_backup_password" {
  secret      = google_secret_manager_secret.nas_backup_password.id
  secret_data = var.nas_backup_password
}
